repos:
  
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-format
        files: ^src/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        files: ^src/.*\.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^src/.*\.py$
        args: [--config-file=mypy.ini]
        additional_dependencies:
          - pydantic>=2.0
          - types-PyYAML>=6.0
          - types-requests==2.32.4.20250913
          - google-genai==1.49.0